amqp:
    username: ENC[AES256_GCM,data:gDohipuhphphGGHpX3iKgUOs=,iv:GFq6URtAPPEX1DPmoaAsayL7+gUhpbbqnuHjLEuHeuk=,tag:9BWZGquh9h0h4J4CgSzqBQ==,type:str]
    password: ENC[AES256_GCM,data:zX7tH/uAaiMV4NnxPwIzEHJWUWiZyy+04g==,iv:Dec4ppy4ErjQ8pO6NphCU6Ba0F73dH203cBP31xc3Go=,tag:TG0EH1cJ41IgXwW2A59U7Q==,type:str]
    host: ENC[AES256_GCM,data:f3FO2z7PhKMJKAMiqeEpJEmQQDELBvzGdvQo3gOmEaM=,iv:T2rZ4aCRKgs6UCRY6cOd7IintWX4tU0GHzpJzYxZTvg=,tag:QFLbqXnIHTuaX3Z6/WaXpQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodal-algebra-161404/locations/global/keyRings/deployment/cryptoKeys/welldev-nlp
          created_at: "2022-05-18T07:32:21Z"
          enc: CiQAErcw8o13k/il1qWFU+5Y80Oc;jjk;kjjjjjzG+JAiHw8lWmH8K5CCsz18ASSQDynIvzXMkg8JNPWtLCPbppgbuBTrnXRPb5vzp770TVoHGfvgtR/J2YeAXb2118mikl7UqQMYU4A9LFHLY30KD6PpOVc/MonlA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-13T12:10:38Z"
    mac: ENC[AES256_GCM,data:xz+LL+BLFNMRGLp2ZAB3BzmJsDnYq+UcALlRnSi5bdrJSvtU9KuzxeDPqYFDMOL7SfB84mP9wAbk/VYNRBc6D2jqZIxyiiOp/wcMDHR10pdq1JcZRioILLioK9R/swp6zdUe0yeUiWiVm9PPgrKvd6Hlk8amxhFJegyvH49hyds=,iv:zbhnFOsiA3vJjatdMNXgVfxFqBtCzSDJlWFlsCCUzw8=,tag:/7aGk+WFR9z3QQ2Ec9nsRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1


password: mime
username: mime