name: Gitleaks Secret Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=. --config-path=gitleaks.toml --report-format=sarif --report-path=gitleaks.sarif

      - name: Upload SARIF report to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
