name: Gitleaks Secret Scanning

on:
  push:
    branches: ['**']  

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        config-path: .gitleaks.toml
        fail-on-secrets: true
        verbose: true
        report-format: text
        path: gitleaks-report.json